language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source

notifications:
  slack:
    secure: "gLPOj3Nbu04euXxNrI+aBo+oXOYZbZIM6ScXNJzUeFWMTBU3O7UcGJAapsbXwdvc/ufb+PJlGl7hwv439S4ej9UDmXwkvosR0dHrnexNQtVscwM0XwP/PaBSBAyJTSY6LyelMlb8/M8fEa8XjsqU6ZmkqmgvRzfAEASJS77O1EaHJVrAafZIY7POOS1ODvd+U+zrj6YpQM13wRpZxUD/ObvcNkym/zZofRmtsdmR/yWHXjn1s7MW5NS8UEydDB1LA7N5JuqcyItnS4eJdiX8D4O5gbOC2+HHPRWxx1BoWYDW5jMWXvc4UW1IF4NwtTIJTGU2Os3wKF7SSBVIZK47BGJBOt+FtrMn23h0luY+HweEde/jDIDIaHuGntPB/KaP8pOJ6oG5UHtsbfUhSgEupu9ftHeYchHlXZVuyn00hv4exkzgVN0NBAGaiFdCCg5mX0CHWcYI8MjUHHVaYVVJQvGEU/u4p2aOB8E7MTESuLO9uI1Xxot6uF1W7z3f0IUIuD7FOXvbH//SARKXo6T8hySWtDafTaNY68jPVwRWalA4ccYzgtEu/LWKhxhJt/FkTDkXaL17wmPrGTyU5mo2zZ8dyTUL/hibesV6YEKLXiFADdsrlyS175tfZrZA5i+bMlUZVyxqgGL88N+BDbp9qrXCrWrDVm4YOEJ7IkWvbmw="

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ -n
  - ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)' https://codeclimate.com/test_reports"